# Generated by Django 5.1 on 2024-10-31 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('confirmation_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='確認コード')),
                ('confirmation_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='確認コード作成日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('userId', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='ユーザーネーム')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名前')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, null=True, verbose_name='性別')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='プロフィール画像')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='身長(cm)')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
