# Generated by Django 5.1 on 2024-11-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('unanswered', '未回答'), ('male', '男性'), ('female', '女性'), ('other', 'その他')], default='unanswered', max_length=10, null=True, verbose_name='性別'),
        ),
    ]
