# Generated by Django 5.1 on 2024-12-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fashion_items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_data', models.JSONField(default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_items.fashionitem')),
            ],
            options={
                'ordering': ['position_data__zIndex'],
            },
        ),
        migrations.CreateModel(
            name='CustomCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('preview_image', models.ImageField(upload_to='coordinations/previews/')),
                ('items', models.ManyToManyField(related_name='coordinates', through='coordinate.CoordinateItem', to='fashion_items.fashionitem')),
                ('seasons', models.ManyToManyField(blank=True, to='fashion_items.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenes', models.ManyToManyField(blank=True, to='coordinate.scene')),
                ('tastes', models.ManyToManyField(blank=True, to='coordinate.taste')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coordinateitem',
            name='coordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_item_set', to='coordinate.customcoordinate'),
        ),
        migrations.CreateModel(
            name='PhotoCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image', models.ImageField(upload_to='coordinations/')),
                ('seasons', models.ManyToManyField(blank=True, to='fashion_items.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scenes', models.ManyToManyField(blank=True, to='coordinate.scene')),
                ('tastes', models.ManyToManyField(blank=True, to='coordinate.taste')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='coordinateitem',
            unique_together={('coordinate', 'item')},
        ),
    ]
