name: backend CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/**
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run backend Docker containers
        working-directory: ./backend
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          TZ: ${{ secrets.TZ }}

        run: |
          docker compose build backend db
          docker compose up -d backend db
          docker compose ps

      - name: Run migrations
        working-directory: ./backend
        run: docker compose exec -T backend python manage.py migrate

      - name: Run Ruff linter
        working-directory: ./backend
        run: docker compose exec -T backend ruff check

      - name: Run Ruff formatter
        working-directory: ./backend
        run: docker compose exec -T backend ruff format

      - name: Run pytest
        working-directory: ./backend
        run: docker compose exec -T backend pytest

      - name: Stop and remove Docker containers
        working-directory: ./backend
        run: docker compose down
# ＊リリース時にはデプロイの設定も
