name: backend CI/CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run Docker containers
        working-directory: ./backend
        run: |
          docker compose build --no-cache
          docker compose up -d
          docker compose ps

      - name: Run migrations
        working-directory: ./backend
        run: docker compose exec -T backend python manage.py migrate

      - name: Run Ruff linter
        working-directory: ./backend
        run: docker compose exec -T backend ruff check

      - name: Run Ruff formatter
        working-directory: ./backend
        run: docker compose exec -T backend ruff format

      - name: Run pytest
        working-directory: ./backend
        run: docker compose exec -T backend pytest

      - name: Stop and remove Docker containers
        working-directory: ./backend
        run: docker compose down
# ＊リリース時にはデプロイの設定も
