name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/**
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          # ルートの .env ファイルを生成
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> .env


          # frontend/.env.local ファイルを生成
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> frontend/.env.local
          echo "NEXT_PUBLIC_ENV=${{ secrets.NEXT_PUBLIC_ENV }}" >> frontend/.env.local

          # backend/.env ファイルを生成
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> backend/.env
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> backend/.env
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> backend/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> backend/.env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> backend/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> backend/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> backend/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/.env
          echo "TZ=${{ secrets.TZ }}" >> backend/.env

      - name: Install bun and Dependencies
        working-directory: ./frontend
        run: |
          npm install -g bun
          bun install

      - name: Build and run frontend Docker container
        working-directory: ./frontend
        run: |
          docker compose build frontend
          docker compose up -d frontend
          docker compose ps

      - name: Install Dependencies
        run: docker compose exec -T frontend bun install
        working-directory: ./frontend

      - name: Run format check
        run: docker compose exec -T frontend bun run format
        working-directory: ./frontend

      - name: Run linter
        run: docker compose exec -T frontend bun run lint
        working-directory: ./frontend

      - name: Run Test
        run: docker compose exec -T frontend bun run test
        working-directory: ./frontend

      - name: Stop and remove Docker containers
        run: docker compose down
        working-directory: ./frontend
# ＊リリース時にはデプロイの設定も
